// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./comprs.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-android-arm64')
        const bindingPackageVersion = require('@derodero24/comprs-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./comprs.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-android-arm-eabi')
        const bindingPackageVersion = require('@derodero24/comprs-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./comprs.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-win32-x64-gnu')
        const bindingPackageVersion = require('@derodero24/comprs-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./comprs.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-win32-x64-msvc')
        const bindingPackageVersion = require('@derodero24/comprs-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./comprs.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-win32-ia32-msvc')
        const bindingPackageVersion = require('@derodero24/comprs-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./comprs.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-win32-arm64-msvc')
        const bindingPackageVersion = require('@derodero24/comprs-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./comprs.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@derodero24/comprs-darwin-universal')
      const bindingPackageVersion = require('@derodero24/comprs-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./comprs.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-darwin-x64')
        const bindingPackageVersion = require('@derodero24/comprs-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./comprs.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-darwin-arm64')
        const bindingPackageVersion = require('@derodero24/comprs-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./comprs.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-freebsd-x64')
        const bindingPackageVersion = require('@derodero24/comprs-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./comprs.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-freebsd-arm64')
        const bindingPackageVersion = require('@derodero24/comprs-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./comprs.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@derodero24/comprs-linux-x64-musl')
          const bindingPackageVersion = require('@derodero24/comprs-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./comprs.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@derodero24/comprs-linux-x64-gnu')
          const bindingPackageVersion = require('@derodero24/comprs-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./comprs.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@derodero24/comprs-linux-arm64-musl')
          const bindingPackageVersion = require('@derodero24/comprs-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./comprs.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@derodero24/comprs-linux-arm64-gnu')
          const bindingPackageVersion = require('@derodero24/comprs-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./comprs.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@derodero24/comprs-linux-arm-musleabihf')
          const bindingPackageVersion = require('@derodero24/comprs-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./comprs.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@derodero24/comprs-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@derodero24/comprs-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./comprs.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@derodero24/comprs-linux-loong64-musl')
          const bindingPackageVersion = require('@derodero24/comprs-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./comprs.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@derodero24/comprs-linux-loong64-gnu')
          const bindingPackageVersion = require('@derodero24/comprs-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./comprs.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@derodero24/comprs-linux-riscv64-musl')
          const bindingPackageVersion = require('@derodero24/comprs-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./comprs.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@derodero24/comprs-linux-riscv64-gnu')
          const bindingPackageVersion = require('@derodero24/comprs-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./comprs.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-linux-ppc64-gnu')
        const bindingPackageVersion = require('@derodero24/comprs-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./comprs.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-linux-s390x-gnu')
        const bindingPackageVersion = require('@derodero24/comprs-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./comprs.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-openharmony-arm64')
        const bindingPackageVersion = require('@derodero24/comprs-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./comprs.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-openharmony-x64')
        const bindingPackageVersion = require('@derodero24/comprs-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./comprs.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@derodero24/comprs-openharmony-arm')
        const bindingPackageVersion = require('@derodero24/comprs-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.4.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./comprs.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('@derodero24/comprs-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.BrotliCompressContext = nativeBinding.BrotliCompressContext
module.exports.BrotliCompressDictContext = nativeBinding.BrotliCompressDictContext
module.exports.BrotliDecompressContext = nativeBinding.BrotliDecompressContext
module.exports.BrotliDecompressDictContext = nativeBinding.BrotliDecompressDictContext
module.exports.DeflateCompressContext = nativeBinding.DeflateCompressContext
module.exports.DeflateDecompressContext = nativeBinding.DeflateDecompressContext
module.exports.GzipCompressContext = nativeBinding.GzipCompressContext
module.exports.GzipDecompressContext = nativeBinding.GzipDecompressContext
module.exports.Lz4CompressContext = nativeBinding.Lz4CompressContext
module.exports.Lz4DecompressContext = nativeBinding.Lz4DecompressContext
module.exports.ZstdCompressContext = nativeBinding.ZstdCompressContext
module.exports.ZstdCompressDictContext = nativeBinding.ZstdCompressDictContext
module.exports.ZstdDecompressContext = nativeBinding.ZstdDecompressContext
module.exports.ZstdDecompressDictContext = nativeBinding.ZstdDecompressDictContext
module.exports.brotliCompress = nativeBinding.brotliCompress
module.exports.brotliCompressAsync = nativeBinding.brotliCompressAsync
module.exports.brotliCompressWithDict = nativeBinding.brotliCompressWithDict
module.exports.brotliCompressWithDictAsync = nativeBinding.brotliCompressWithDictAsync
module.exports.brotliDecompress = nativeBinding.brotliDecompress
module.exports.brotliDecompressAsync = nativeBinding.brotliDecompressAsync
module.exports.brotliDecompressWithCapacity = nativeBinding.brotliDecompressWithCapacity
module.exports.brotliDecompressWithCapacityAsync = nativeBinding.brotliDecompressWithCapacityAsync
module.exports.brotliDecompressWithDict = nativeBinding.brotliDecompressWithDict
module.exports.brotliDecompressWithDictAsync = nativeBinding.brotliDecompressWithDictAsync
module.exports.brotliDecompressWithDictWithCapacity = nativeBinding.brotliDecompressWithDictWithCapacity
module.exports.brotliDecompressWithDictWithCapacityAsync = nativeBinding.brotliDecompressWithDictWithCapacityAsync
module.exports.CompressionFormat = nativeBinding.CompressionFormat
module.exports.crc32 = nativeBinding.crc32
module.exports.decompress = nativeBinding.decompress
module.exports.decompressAsync = nativeBinding.decompressAsync
module.exports.deflateCompress = nativeBinding.deflateCompress
module.exports.deflateCompressAsync = nativeBinding.deflateCompressAsync
module.exports.deflateDecompress = nativeBinding.deflateDecompress
module.exports.deflateDecompressAsync = nativeBinding.deflateDecompressAsync
module.exports.deflateDecompressWithCapacity = nativeBinding.deflateDecompressWithCapacity
module.exports.deflateDecompressWithCapacityAsync = nativeBinding.deflateDecompressWithCapacityAsync
module.exports.detectFormat = nativeBinding.detectFormat
module.exports.gzipCompress = nativeBinding.gzipCompress
module.exports.gzipCompressAsync = nativeBinding.gzipCompressAsync
module.exports.gzipCompressWithHeader = nativeBinding.gzipCompressWithHeader
module.exports.gzipDecompress = nativeBinding.gzipDecompress
module.exports.gzipDecompressAsync = nativeBinding.gzipDecompressAsync
module.exports.gzipDecompressWithCapacity = nativeBinding.gzipDecompressWithCapacity
module.exports.gzipDecompressWithCapacityAsync = nativeBinding.gzipDecompressWithCapacityAsync
module.exports.gzipReadHeader = nativeBinding.gzipReadHeader
module.exports.lz4Compress = nativeBinding.lz4Compress
module.exports.lz4CompressAsync = nativeBinding.lz4CompressAsync
module.exports.lz4Decompress = nativeBinding.lz4Decompress
module.exports.lz4DecompressAsync = nativeBinding.lz4DecompressAsync
module.exports.lz4DecompressWithCapacity = nativeBinding.lz4DecompressWithCapacity
module.exports.lz4DecompressWithCapacityAsync = nativeBinding.lz4DecompressWithCapacityAsync
module.exports.version = nativeBinding.version
module.exports.zstdCompress = nativeBinding.zstdCompress
module.exports.zstdCompressAsync = nativeBinding.zstdCompressAsync
module.exports.zstdCompressWithDict = nativeBinding.zstdCompressWithDict
module.exports.zstdCompressWithDictAsync = nativeBinding.zstdCompressWithDictAsync
module.exports.zstdDecompress = nativeBinding.zstdDecompress
module.exports.zstdDecompressAsync = nativeBinding.zstdDecompressAsync
module.exports.zstdDecompressWithCapacity = nativeBinding.zstdDecompressWithCapacity
module.exports.zstdDecompressWithCapacityAsync = nativeBinding.zstdDecompressWithCapacityAsync
module.exports.zstdDecompressWithDict = nativeBinding.zstdDecompressWithDict
module.exports.zstdDecompressWithDictAsync = nativeBinding.zstdDecompressWithDictAsync
module.exports.zstdDecompressWithDictWithCapacity = nativeBinding.zstdDecompressWithDictWithCapacity
module.exports.zstdTrainDictionary = nativeBinding.zstdTrainDictionary
module.exports.zstdTrainDictionaryAsync = nativeBinding.zstdTrainDictionaryAsync
