/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Streaming zstd compression context.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * enabling chunked compression without losing cross-chunk context.
 */
export declare class ZstdCompressContext {
  constructor(level?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the encoder is buffering data internally).
   */
  transform(chunk: Buffer): Buffer
  /** Flush the encoder's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the compression stream. Writes the zstd frame footer.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
}

/**
 * Streaming zstd decompression context.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * enabling chunked decompression of a zstd frame.
 */
export declare class ZstdDecompressContext {
  constructor()
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decoder needs more data).
   */
  transform(chunk: Buffer): Buffer
  /** Flush the decoder's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
}

/** Returns the library version. */
export declare function version(): string

/**
 * Compress data using Zstandard.
 *
 * Returns the compressed data as a Buffer.
 * Level ranges from 1 (fastest) to 22 (best compression). Default is 3.
 * Negative levels (e.g., -1 to -131072) enable fast mode, trading compression
 * ratio for speed. Level 0 is equivalent to the default level (3).
 */
export declare function zstdCompress(data: Buffer, level?: number | undefined | null): Buffer

/**
 * Decompress Zstandard-compressed data.
 *
 * Returns the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `zstdDecompressWithCapacity`
 * for larger data.
 */
export declare function zstdDecompress(data: Buffer): Buffer

/**
 * Decompress Zstandard-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function zstdDecompressWithCapacity(data: Buffer, capacity: number): Buffer
