/* auto-generated by NAPI-RS */
/* eslint-disable */

// This header comes from crates/core/dts-header.d.ts ("dtsHeaderFile" in
// package.json). When the addon loads, it aliases [Symbol.dispose]() to
// close() on the stream context classes (crates/core/src/context.rs), which
// the declarations that napi-rs generates from the Rust code cannot express.

export interface BrotliCompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface BrotliCompressDictContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface BrotliDecompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface BrotliDecompressDictContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface DeflateCompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface DeflateDecompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface GzipCompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface GzipDecompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface Lz4CompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface Lz4DecompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface ZstdCompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface ZstdCompressDictContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface ZstdDecompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface ZstdDecompressDictContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Streaming brotli compression context.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * enabling chunked compression without losing cross-chunk context.
 */
export declare class BrotliCompressContext {
  constructor(quality?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the compressor is buffering data internally).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the compressor's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the compression stream. Writes the brotli stream footer.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming brotli compression context with custom dictionary.
 *
 * Buffers all input and compresses with the dictionary on `finish`.
 * This is necessary because the brotli CompressorWriter does not expose
 * a dictionary API; dictionary compression requires the low-level encoder.
 */
export declare class BrotliCompressDictContext {
  constructor(dict: Buffer | Uint8Array, quality?: number | undefined | null)
  /**
   * Buffer a chunk of data for compression. Returns an empty Buffer because
   * all compression is deferred to `finish` (dictionary requires one-shot).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush returns empty Buffer because all data is buffered until finish. */
  flush(): Buffer
  /**
   * Finalize the compression. Compresses all buffered data with the dictionary.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming brotli decompression context.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * enabling chunked decompression of a brotli stream.
 */
export declare class BrotliDecompressContext {
  constructor(maxOutputSize?: number | undefined | null)
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decompressor needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decompressor's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
  /**
   * Finalize the decompression stream. Returns any remaining decompressed data.
   * Throws if the input ended before the end of the brotli stream, including empty input.
   * Must be called once after all compressed data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming brotli decompression context with custom dictionary.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * using a custom dictionary that matches the one used for compression.
 */
export declare class BrotliDecompressDictContext {
  constructor(dict: Buffer | Uint8Array, maxOutputSize?: number | undefined | null)
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decompressor needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decompressor's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
  /**
   * Finalize the decompression stream. Returns any remaining decompressed data.
   * Throws if the input ended before the end of the brotli stream, including empty input.
   * Must be called once after all compressed data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming raw deflate compression context.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * enabling chunked deflate compression without losing cross-chunk context.
 */
export declare class DeflateCompressContext {
  constructor(level?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the encoder is buffering data internally).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the encoder's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the deflate stream.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming raw deflate decompression context.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * enabling chunked decompression of a raw deflate stream.
 */
export declare class DeflateDecompressContext {
  constructor(maxOutputSize?: number | undefined | null)
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decoder needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decoder's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
  /**
   * Finalize the deflate decompression stream.
   * Throws if the input ended before the final deflate block, including empty input.
   * Must be called once after all compressed data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming gzip compression context.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * enabling chunked gzip compression without losing cross-chunk context.
 */
export declare class GzipCompressContext {
  constructor(level?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the encoder is buffering data internally).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the encoder's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the gzip stream. Writes the gzip footer (CRC32 + size).
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming gzip decompression context.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * enabling chunked decompression of a gzip stream.
 */
export declare class GzipDecompressContext {
  constructor(maxOutputSize?: number | undefined | null)
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decoder needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decoder's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
  /**
   * Finalize the gzip decompression stream and verify CRC integrity.
   * Throws if the input is truncated, including empty input.
   * Must be called once after all compressed data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming LZ4 frame compression context.
 *
 * Compresses into independent blocks of up to 64 KiB and returns the
 * output of each block once the block is complete; `flush()` completes the
 * current block early. The frame carries a content checksum, as the `lz4`
 * CLI writes by default.
 */
export declare class Lz4CompressContext {
  constructor()
  /** Compress a chunk of data. Returns any compressed output produced so far. */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the encoder's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the compression stream. Writes the LZ4 frame footer.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming LZ4 frame decompression context.
 *
 * The input may hold several concatenated frames, including skippable and
 * legacy frames. The context works in one of two modes:
 *
 * - By default, it buffers its input: `transform()` keeps each chunk and
 *   returns an empty buffer, and `flush()` decodes what has been kept since
 *   the last `flush()`, which must end between frames. `maxOutputSize`
 *   limits the output of each `flush()` on its own, not of the whole stream.
 * - With `{ incremental: true }`, it decodes its input as it arrives:
 *   `transform()` returns the content of each block once all of the block
 *   has arrived, and throws as soon as the input is invalid; `flush()`
 *   returns an empty buffer; `finish()` throws if the input did not end
 *   between frames. `maxOutputSize` limits the output of the whole stream,
 *   and the context keeps at most one block of input. The stream helpers
 *   use this mode.
 */
export declare class Lz4DecompressContext {
  /**
   * `maxOutputSize` defaults to 256 MB. `options.incremental` selects the
   * incremental mode; `options` must be an object, `undefined` or `null`.
   */
  constructor(maxOutputSize?: number | undefined | null, options?: StreamContextOptions | undefined | null)
  /**
   * Take a chunk of compressed data. By default, keep it and return an
   * empty buffer: the output comes from `flush()`. Incremental, return the
   * content of the blocks that the chunk completes, and throw if the
   * input is invalid or the output exceeds `maxOutputSize`.
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /**
   * By default, decompress all buffered data and return the result, with
   * at most `maxOutputSize` bytes. Throws if no compressed data was
   * transformed at all, if the input ends inside a frame, or if data that
   * is not a frame follows a frame. Incremental, return an empty buffer.
   */
  flush(): Buffer
  /**
   * Finalize the decompression stream, then release the native state.
   * By default, decompress the data buffered since the last `flush()`,
   * like `flush()`. Incremental, return an empty buffer, or throw if the
   * input did not end between frames, including empty input. Throws if
   * the stream is already finished.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming zstd compression context.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * enabling chunked compression without losing cross-chunk context.
 */
export declare class ZstdCompressContext {
  constructor(level?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the encoder is buffering data internally).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the encoder's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the compression stream. Writes the zstd frame footer.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming zstd compression context with dictionary.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * using a pre-trained dictionary for improved compression of small, similar data.
 */
export declare class ZstdCompressDictContext {
  constructor(dict: Buffer | Uint8Array, level?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the encoder is buffering data internally).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the encoder's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the compression stream. Writes the zstd frame footer.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming zstd decompression context.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * enabling chunked decompression of a zstd frame.
 *
 * `maxOutputSize` limits the decompressed size in bytes, 256 MB by default.
 * It also bounds the window that a frame makes the decoder allocate before
 * it writes any output: to `maxOutputSize` rounded up to a power of two, at
 * least 8 MiB and at most zstd's default of 128 MiB, so a frame that
 * declares a larger window throws an error instead.
 */
export declare class ZstdDecompressContext {
  constructor(maxOutputSize?: number | undefined | null)
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decoder needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decoder's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
  /**
   * Finalize the decompression stream. Returns any remaining decompressed data.
   * Throws if the input ended before the end of a zstd frame, including empty input.
   * Must be called once after all compressed data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Streaming zstd decompression context with dictionary.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * using a pre-trained dictionary that matches the one used for compression.
 *
 * `maxOutputSize` limits the decompressed size in bytes, 256 MB by default.
 * It also bounds the window that a frame makes the decoder allocate before
 * it writes any output: to `maxOutputSize` rounded up to a power of two, at
 * least 8 MiB and at most zstd's default of 128 MiB, so a frame that
 * declares a larger window throws an error instead.
 */
export declare class ZstdDecompressDictContext {
  constructor(dict: Buffer | Uint8Array, maxOutputSize?: number | undefined | null)
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decoder needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decoder's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
  /**
   * Finalize the decompression stream. Returns any remaining decompressed data.
   * Throws if the input ended before the end of a zstd frame, including empty input.
   * Must be called once after all compressed data has been transformed.
   */
  finish(): Buffer
  /**
   * Release the native state of the context now rather than when the
   * context is garbage-collected. Later calls throw, and `finish()`
   * releases the state too. Closing a finished or closed context does
   * nothing. `[Symbol.dispose]()` is the same method, for `using`
   * declarations.
   */
  close(): void
}

/**
 * Compress data using Brotli.
 *
 * Returns the compressed data as a Buffer.
 * Quality is an integer from 0 (fastest) to 11 (best compression). Default
 * is 6.
 */
export declare function brotliCompress(data: Buffer | Uint8Array, quality?: number | undefined | null): Buffer

/**
 * Asynchronously compress data using Brotli.
 *
 * Returns a Promise that resolves to the compressed data as a Buffer.
 * Quality is an integer from 0 (fastest) to 11 (best compression). Default
 * is 6.
 */
export declare function brotliCompressAsync(data: Buffer | Uint8Array, quality?: number | undefined | null): Promise<Buffer>

/**
 * Compress data using Brotli with a custom dictionary.
 *
 * The same dictionary must be used for decompression via `brotliDecompressWithDict`.
 * Quality is an integer from 0 (fastest) to 11 (best compression). Default
 * is 6.
 */
export declare function brotliCompressWithDict(data: Buffer | Uint8Array, dict: Buffer | Uint8Array, quality?: number | undefined | null): Buffer

/**
 * Asynchronously compress data using Brotli with a custom dictionary.
 *
 * The same dictionary must be used for decompression via `brotliDecompressWithDict`.
 * Quality is an integer from 0 (fastest) to 11 (best compression). Default
 * is 6.
 */
export declare function brotliCompressWithDictAsync(data: Buffer | Uint8Array, dict: Buffer | Uint8Array, quality?: number | undefined | null): Promise<Buffer>

/**
 * Decompress Brotli-compressed data.
 *
 * Returns the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB.
 */
export declare function brotliDecompress(data: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress Brotli-compressed data.
 *
 * Returns a Promise that resolves to the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB.
 */
export declare function brotliDecompressAsync(data: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress Brotli-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function brotliDecompressWithCapacity(data: Buffer | Uint8Array, capacity: number): Buffer

/**
 * Asynchronously decompress Brotli-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function brotliDecompressWithCapacityAsync(data: Buffer | Uint8Array, capacity: number): Promise<Buffer>

/**
 * Decompress Brotli-compressed data that was compressed with a custom dictionary.
 *
 * The same dictionary used for compression must be provided.
 */
export declare function brotliDecompressWithDict(data: Buffer | Uint8Array, dict: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress Brotli-compressed data that was compressed with a custom dictionary.
 *
 * The same dictionary used for compression must be provided.
 */
export declare function brotliDecompressWithDictAsync(data: Buffer | Uint8Array, dict: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress Brotli-compressed data that was compressed with a custom dictionary,
 * with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 * The same dictionary used for compression must be provided.
 */
export declare function brotliDecompressWithDictWithCapacity(data: Buffer | Uint8Array, dict: Buffer | Uint8Array, capacity: number): Buffer

/**
 * Asynchronously decompress Brotli-compressed data that was compressed with a custom dictionary,
 * with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 * The same dictionary used for compression must be provided.
 */
export declare function brotliDecompressWithDictWithCapacityAsync(data: Buffer | Uint8Array, dict: Buffer | Uint8Array, capacity: number): Promise<Buffer>

/**
 * Compression format detected from input data.
 *
 * Compare a result with the members, such as `CompressionFormat.Zstd`, or
 * with their values, the strings `'zstd'`, `'gzip'`, `'brotli'`, `'lz4'` and
 * `'unknown'`. The members of the runtime object are not enumerable
 * (`Object.keys()` and `Object.values()` return `[]`), so use them by name.
 */
export declare enum CompressionFormat {
  Zstd = 'zstd',
  Gzip = 'gzip',
  Brotli = 'brotli',
  Lz4 = 'lz4',
  Unknown = 'unknown',
}

/**
 * Compute CRC32 checksum of the given data.
 *
 * Optionally accepts an initial CRC value for incremental computation:
 * split data into chunks, pass the result of each chunk as `initial_value`
 * for the next. `initial_value` is an integer from 0 to 4294967295.
 */
export declare function crc32(data: Buffer | Uint8Array, initialValue?: number | undefined | null): number

/**
 * Decompress data by auto-detecting the compression format.
 *
 * Detects the format like `detectFormat` and decompresses using the
 * appropriate algorithm.
 *
 * `maxOutputSize` limits the decompressed size in bytes, like the
 * `maxOutputSize` of `createDecompressStream`. It defaults to 256 MB for all
 * formats. It is only a limit: a large value reserves no memory up front.
 * For zstd input, it also bounds the window of a frame, as the `capacity` of
 * `zstdDecompressWithCapacity` does.
 *
 * Supported formats: zstd, gzip, brotli, lz4.
 * Raw deflate is not supported (no magic bytes to distinguish it).
 * Data detected as brotli that does not decode as brotli throws the same
 * error as data of unknown format, since brotli detection is heuristic.
 */
export declare function decompress(data: Buffer | Uint8Array, maxOutputSize?: number | undefined | null): Buffer

/**
 * Asynchronously decompress data by auto-detecting the compression format.
 *
 * Detects the format like `detectFormat` and decompresses using the
 * appropriate algorithm. Returns a Promise that resolves to the
 * decompressed data as a Buffer.
 *
 * `maxOutputSize` limits the decompressed size in bytes, as for
 * `decompress`. It defaults to 256 MB.
 *
 * Supported formats: zstd, gzip, brotli, lz4.
 * Raw deflate is not supported (no magic bytes to distinguish it).
 * Data detected as brotli that does not decode as brotli rejects with the
 * same error as data of unknown format, since brotli detection is heuristic.
 */
export declare function decompressAsync(data: Buffer | Uint8Array, maxOutputSize?: number | undefined | null): Promise<Buffer>

/**
 * Compress data using raw deflate (no gzip header/trailer).
 *
 * Returns the compressed data as a Buffer.
 * Level is an integer from 0 (no compression) to 9 (best compression).
 * Default is 6.
 */
export declare function deflateCompress(data: Buffer | Uint8Array, level?: number | undefined | null): Buffer

/**
 * Asynchronously compress data using raw deflate (no gzip header/trailer).
 *
 * Returns a Promise that resolves to the compressed data as a Buffer.
 * Level is an integer from 0 (no compression) to 9 (best compression).
 * Default is 6.
 */
export declare function deflateCompressAsync(data: Buffer | Uint8Array, level?: number | undefined | null): Promise<Buffer>

/**
 * Decompress raw deflate-compressed data.
 *
 * Returns the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `deflateDecompressWithCapacity`
 * for larger data. Throws if the input ends before the final deflate block.
 */
export declare function deflateDecompress(data: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress raw deflate-compressed data.
 *
 * Returns a Promise that resolves to the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `deflateDecompressWithCapacity`
 * for larger data. Rejects if the input ends before the final deflate block.
 */
export declare function deflateDecompressAsync(data: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress raw deflate-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 * Throws if the input ends before the final deflate block.
 */
export declare function deflateDecompressWithCapacity(data: Buffer | Uint8Array, capacity: number): Buffer

/**
 * Asynchronously decompress raw deflate-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 * Rejects if the input ends before the final deflate block.
 */
export declare function deflateDecompressWithCapacityAsync(data: Buffer | Uint8Array, capacity: number): Promise<Buffer>

/**
 * Detect the compression format of the given data.
 *
 * Returns `"zstd"`, `"gzip"`, `"brotli"`, or `"lz4"`.
 * Returns `"unknown"` if the format cannot be determined.
 *
 * zstd, gzip and LZ4 are recognized by their magic numbers, LZ4 legacy
 * frames (`lz4 -l`) included. Skippable frames at the start of the data,
 * which zstd and LZ4 share, are skipped: the frame after them decides.
 *
 * Brotli has no magic number, so it is detected heuristically: up to the
 * first 64 KiB of the data are decoded, and the data is reported as
 * `"brotli"` if they decode without error and either hold a whole brotli
 * stream that ends with the data, decode to more bytes than they hold, or
 * fill the 64 KiB. The start of a brotli stream of data that does not
 * compress is thus reported as `"unknown"` until it is 64 KiB long, and
 * about 5% of random data of 64 KiB or more is reported as `"brotli"`.
 * Raw deflate has no magic number and is not detected.
 */
export declare function detectFormat(data: Buffer | Uint8Array): CompressionFormat

/**
 * Compress data using gzip.
 *
 * Returns the compressed data as a Buffer.
 * Level is an integer from 0 (no compression) to 9 (best compression).
 * Default is 6.
 */
export declare function gzipCompress(data: Buffer | Uint8Array, level?: number | undefined | null): Buffer

/**
 * Asynchronously compress data using gzip.
 *
 * Returns a Promise that resolves to the compressed data as a Buffer.
 * Level is an integer from 0 (no compression) to 9 (best compression).
 * Default is 6.
 */
export declare function gzipCompressAsync(data: Buffer | Uint8Array, level?: number | undefined | null): Promise<Buffer>

/**
 * Compress data using gzip with custom header metadata.
 *
 * Allows setting header fields such as `filename` and `mtime`. Throws if
 * `filename` contains a NUL character or is longer than 65535 bytes in UTF-8.
 * Returns the compressed data as a Buffer.
 * Level is an integer from 0 (no compression) to 9 (best compression).
 * Default is 6.
 */
export declare function gzipCompressWithHeader(data: Buffer | Uint8Array, header: GzipHeaderOptions, level?: number | undefined | null): Buffer

/**
 * Decompress gzip-compressed data.
 *
 * Returns the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `gzipDecompressWithCapacity`
 * for larger data.
 */
export declare function gzipDecompress(data: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress gzip-compressed data.
 *
 * Returns a Promise that resolves to the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `gzipDecompressWithCapacity`
 * for larger data.
 */
export declare function gzipDecompressAsync(data: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress gzip-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function gzipDecompressWithCapacity(data: Buffer | Uint8Array, capacity: number): Buffer

/**
 * Asynchronously decompress gzip-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function gzipDecompressWithCapacityAsync(data: Buffer | Uint8Array, capacity: number): Promise<Buffer>

/** Parsed gzip header metadata. */
export interface GzipHeader {
  /** Original filename stored in the header, if present. */
  filename?: string
  /** Modification time as a Unix timestamp (seconds since epoch). */
  mtime: number
  /** Comment stored in the header, if present. */
  comment?: string
  /** Operating system that created the gzip stream. */
  os: number
  /** Extra field data, if present. */
  extra?: Buffer
}

/** Options for customizing the gzip header during compression. */
export interface GzipHeaderOptions {
  /**
   * Original filename to store in the gzip header. It must not contain NUL
   * characters and must be at most 65535 bytes long in UTF-8.
   */
  filename?: string
  /**
   * Modification time as a Unix timestamp (seconds since epoch), an
   * integer from 0 to 4294967295.
   */
  mtime?: number
}

/**
 * Read gzip header metadata without fully decompressing the data.
 *
 * Returns the parsed header fields including filename, mtime, comment, OS, and extra data.
 */
export declare function gzipReadHeader(data: Buffer | Uint8Array): GzipHeader

/**
 * Compress data using LZ4 frame format.
 *
 * Returns the compressed data as a Buffer. The frame carries a content
 * checksum, as the `lz4` CLI writes by default.
 */
export declare function lz4Compress(data: Buffer | Uint8Array): Buffer

/**
 * Asynchronously compress data using LZ4 frame format.
 *
 * Returns a Promise that resolves to the compressed data as a Buffer. The
 * frame carries a content checksum, as the `lz4` CLI writes by default.
 */
export declare function lz4CompressAsync(data: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress LZ4 frame-compressed data.
 *
 * Returns the decompressed data as a Buffer.
 * The input may hold several concatenated frames, including skippable and
 * legacy frames. The maximum decompressed size is 256 MB. Use
 * `lz4DecompressWithCapacity` for larger data.
 */
export declare function lz4Decompress(data: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress LZ4 frame-compressed data.
 *
 * Returns a Promise that resolves to the decompressed data as a Buffer.
 * The input may hold several concatenated frames, including skippable and
 * legacy frames. The maximum decompressed size is 256 MB. Use
 * `lz4DecompressWithCapacityAsync` for larger data.
 */
export declare function lz4DecompressAsync(data: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress LZ4 frame-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function lz4DecompressWithCapacity(data: Buffer | Uint8Array, capacity: number): Buffer

/**
 * Asynchronously decompress LZ4 frame-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function lz4DecompressWithCapacityAsync(data: Buffer | Uint8Array, capacity: number): Promise<Buffer>

/**
 * Options of a stream context.
 *
 * Only `Lz4DecompressContext` takes them so far.
 */
export interface StreamContextOptions {
  /**
   * Decode the input as it arrives. With `incremental: true`,
   * `transform()` returns the output of the input as soon as it is
   * available (each LZ4 block once all of it has arrived), `flush()`
   * returns nothing more, and `maxOutputSize` limits the output of the
   * whole stream. Without it, the context keeps the behaviour that it has
   * always had. The stream helpers of `@derodero24/comprs/streams` and
   * `@derodero24/comprs/node` set it.
   */
  incremental?: boolean | undefined
}

/** Returns the library version. */
export declare function version(): string

/**
 * Compress data using Zstandard.
 *
 * Returns the compressed data as a Buffer.
 * Level is an integer from 1 (fastest) to 22 (best compression). Default is
 * 3. Negative levels (-1 to -131072) enable fast mode, trading compression
 * ratio for speed. Level 0 is equivalent to the default level (3).
 */
export declare function zstdCompress(data: Buffer | Uint8Array, level?: number | undefined | null): Buffer

/**
 * Asynchronously compress data using Zstandard.
 *
 * Returns a Promise that resolves to the compressed data as a Buffer.
 * Level is an integer from 1 (fastest) to 22 (best compression). Default is
 * 3. Negative levels (-1 to -131072) enable fast mode, trading compression
 * ratio for speed. Level 0 is equivalent to the default level (3).
 */
export declare function zstdCompressAsync(data: Buffer | Uint8Array, level?: number | undefined | null): Promise<Buffer>

/**
 * Compress data using Zstandard with a pre-trained dictionary.
 *
 * The same dictionary must be used for decompression via `zstdDecompressWithDict`.
 * Level is an integer from -131072 to 22, as for `zstdCompress`. Default is
 * 3.
 */
export declare function zstdCompressWithDict(data: Buffer | Uint8Array, dict: Buffer | Uint8Array, level?: number | undefined | null): Buffer

/**
 * Asynchronously compress data using Zstandard with a pre-trained dictionary.
 *
 * The same dictionary must be used for decompression via `zstdDecompressWithDict`.
 * Level is an integer from -131072 to 22, as for `zstdCompress`. Default is
 * 3.
 */
export declare function zstdCompressWithDictAsync(data: Buffer | Uint8Array, dict: Buffer | Uint8Array, level?: number | undefined | null): Promise<Buffer>

/**
 * Decompress Zstandard-compressed data.
 *
 * Returns the decompressed data as a Buffer.
 * The input may hold several concatenated frames, including skippable
 * frames. The maximum decompressed size is 256 MB. Use
 * `zstdDecompressWithCapacity` for larger data.
 */
export declare function zstdDecompress(data: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress Zstandard-compressed data.
 *
 * Returns a Promise that resolves to the decompressed data as a Buffer.
 * The input may hold several concatenated frames, including skippable
 * frames. The maximum decompressed size is 256 MB. Use
 * `zstdDecompressWithCapacity` for larger data.
 */
export declare function zstdDecompressAsync(data: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress Zstandard-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 * It is only a limit: the output buffer grows with the decompressed data, so
 * a large `capacity` reserves no memory up front. `capacity` also bounds the
 * window that a frame makes the decoder allocate before it writes any
 * output: to `capacity` rounded up to a power of two, at least 8 MiB and at
 * most zstd's default of 128 MiB, so a frame that declares a larger window
 * throws an error instead.
 */
export declare function zstdDecompressWithCapacity(data: Buffer | Uint8Array, capacity: number): Buffer

/**
 * Asynchronously decompress Zstandard-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 * It is only a limit: the output buffer grows with the decompressed data, so
 * a large `capacity` reserves no memory up front. `capacity` also bounds the
 * window that a frame makes the decoder allocate before it writes any
 * output: to `capacity` rounded up to a power of two, at least 8 MiB and at
 * most zstd's default of 128 MiB, so for a frame that declares a larger
 * window the promise rejects with an error instead.
 */
export declare function zstdDecompressWithCapacityAsync(data: Buffer | Uint8Array, capacity: number): Promise<Buffer>

/**
 * Decompress Zstandard-compressed data that was compressed with a dictionary.
 *
 * The same dictionary used for compression must be provided.
 */
export declare function zstdDecompressWithDict(data: Buffer | Uint8Array, dict: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress Zstandard-compressed data that was compressed with a dictionary.
 *
 * The same dictionary used for compression must be provided.
 */
export declare function zstdDecompressWithDictAsync(data: Buffer | Uint8Array, dict: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress Zstandard-compressed data that was compressed with a dictionary,
 * with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 * It is only a limit: the output buffer grows with the decompressed data, so
 * a large `capacity` reserves no memory up front. `capacity` also bounds the
 * window that a frame makes the decoder allocate before it writes any
 * output: to `capacity` rounded up to a power of two, at least 8 MiB and at
 * most zstd's default of 128 MiB, so a frame that declares a larger window
 * throws an error instead.
 * The same dictionary used for compression must be provided.
 */
export declare function zstdDecompressWithDictWithCapacity(data: Buffer | Uint8Array, dict: Buffer | Uint8Array, capacity: number): Buffer

/**
 * Asynchronously decompress Zstandard-compressed data that was compressed with a dictionary,
 * with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 * It is only a limit: the output buffer grows with the decompressed data, so
 * a large `capacity` reserves no memory up front. `capacity` also bounds the
 * window that a frame makes the decoder allocate before it writes any
 * output: to `capacity` rounded up to a power of two, at least 8 MiB and at
 * most zstd's default of 128 MiB, so for a frame that declares a larger
 * window the promise rejects with an error instead.
 * The same dictionary used for compression must be provided.
 */
export declare function zstdDecompressWithDictWithCapacityAsync(data: Buffer | Uint8Array, dict: Buffer | Uint8Array, capacity: number): Promise<Buffer>

/**
 * Train a zstd dictionary from sample data.
 *
 * The dictionary can be used with `zstdCompressWithDict` and `zstdDecompressWithDict`
 * to achieve better compression ratios on small, similar data.
 *
 * `maxDictSize` is optional and defaults to 110 KB (the zstd default). It
 * must not exceed 16 MiB (16777216 bytes).
 */
export declare function zstdTrainDictionary(samples: Array<Buffer | Uint8Array>, maxDictSize?: number | undefined | null): Buffer

/**
 * Asynchronously train a zstd dictionary from sample data.
 *
 * The dictionary can be used with `zstdCompressWithDict` and `zstdDecompressWithDict`
 * to achieve better compression ratios on small, similar data.
 *
 * `maxDictSize` is optional and defaults to 110 KB (the zstd default). It
 * must not exceed 16 MiB (16777216 bytes).
 */
export declare function zstdTrainDictionaryAsync(samples: Array<Buffer | Uint8Array>, maxDictSize?: number | undefined | null): Promise<Buffer>
