import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const binding = require('./index.js');
const streams = require('./streams.js');

export const {
  version,
  crc32,
  brotliCompress,
  brotliDecompress,
  brotliDecompressWithCapacity,
  brotliCompressAsync,
  brotliCompressWithDict,
  brotliCompressWithDictAsync,
  brotliDecompressAsync,
  brotliDecompressWithCapacityAsync,
  brotliDecompressWithDict,
  brotliDecompressWithDictAsync,
  brotliDecompressWithDictWithCapacity,
  brotliDecompressWithDictWithCapacityAsync,
  BrotliCompressContext,
  BrotliDecompressContext,
  BrotliCompressDictContext,
  BrotliDecompressDictContext,
  zstdCompress,
  zstdDecompress,
  zstdDecompressWithCapacity,
  zstdCompressAsync,
  zstdDecompressAsync,
  zstdDecompressWithCapacityAsync,
  zstdCompressWithDictAsync,
  zstdDecompressWithDictAsync,
  zstdTrainDictionaryAsync,
  ZstdCompressContext,
  ZstdDecompressContext,
  ZstdCompressDictContext,
  ZstdDecompressDictContext,
  zstdTrainDictionary,
  zstdCompressWithDict,
  zstdDecompressWithDict,
  CompressionFormat,
  decompress,
  decompressAsync,
  detectFormat,
  gzipCompress,
  gzipCompressWithHeader,
  gzipReadHeader,
  gzipDecompress,
  gzipDecompressWithCapacity,
  gzipCompressAsync,
  gzipDecompressAsync,
  gzipDecompressWithCapacityAsync,
  deflateCompress,
  deflateDecompress,
  deflateDecompressWithCapacity,
  deflateCompressAsync,
  deflateDecompressAsync,
  deflateDecompressWithCapacityAsync,
  GzipCompressContext,
  GzipDecompressContext,
  DeflateCompressContext,
  DeflateDecompressContext,
  lz4Compress,
  lz4Decompress,
  lz4DecompressWithCapacity,
  lz4CompressAsync,
  lz4DecompressAsync,
  lz4DecompressWithCapacityAsync,
  Lz4CompressContext,
  Lz4DecompressContext,
} = binding;

export const {
  createBrotliCompressStream,
  createBrotliDecompressStream,
  createBrotliCompressDictStream,
  createBrotliDecompressDictStream,
  createZstdCompressStream,
  createZstdDecompressStream,
  createZstdCompressDictStream,
  createZstdDecompressDictStream,
  createGzipCompressStream,
  createGzipDecompressStream,
  createDeflateCompressStream,
  createDeflateDecompressStream,
  createLz4CompressStream,
  createLz4DecompressStream,
  createDecompressStream,
} = streams;
