/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Streaming brotli compression context.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * enabling chunked compression without losing cross-chunk context.
 */
export declare class BrotliCompressContext {
  constructor(quality?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the compressor is buffering data internally).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the compressor's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the compression stream. Writes the brotli stream footer.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
}

/**
 * Streaming brotli decompression context.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * enabling chunked decompression of a brotli stream.
 */
export declare class BrotliDecompressContext {
  constructor()
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decompressor needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decompressor's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
}

/**
 * Streaming raw deflate compression context.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * enabling chunked deflate compression without losing cross-chunk context.
 */
export declare class DeflateCompressContext {
  constructor(level?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the encoder is buffering data internally).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the encoder's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the deflate stream.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
}

/**
 * Streaming raw deflate decompression context.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * enabling chunked decompression of a raw deflate stream.
 */
export declare class DeflateDecompressContext {
  constructor()
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decoder needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decoder's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
  /**
   * Finalize the deflate decompression stream.
   * Must be called once after all compressed data has been transformed.
   */
  finish(): Buffer
}

/**
 * Streaming gzip compression context.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * enabling chunked gzip compression without losing cross-chunk context.
 */
export declare class GzipCompressContext {
  constructor(level?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the encoder is buffering data internally).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the encoder's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the gzip stream. Writes the gzip footer (CRC32 + size).
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
}

/**
 * Streaming gzip decompression context.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * enabling chunked decompression of a gzip stream.
 */
export declare class GzipDecompressContext {
  constructor()
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decoder needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decoder's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
  /**
   * Finalize the gzip decompression stream and verify CRC integrity.
   * Must be called once after all compressed data has been transformed.
   */
  finish(): Buffer
}

/**
 * Streaming zstd compression context.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * enabling chunked compression without losing cross-chunk context.
 */
export declare class ZstdCompressContext {
  constructor(level?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the encoder is buffering data internally).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the encoder's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the compression stream. Writes the zstd frame footer.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
}

/**
 * Streaming zstd compression context with dictionary.
 *
 * Maintains internal compression state across multiple `transform` calls,
 * using a pre-trained dictionary for improved compression of small, similar data.
 */
export declare class ZstdCompressDictContext {
  constructor(dict: Buffer | Uint8Array, level?: number | undefined | null)
  /**
   * Compress a chunk of data. Returns compressed output (may be empty if
   * the encoder is buffering data internally).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the encoder's internal buffer. Returns any buffered compressed data. */
  flush(): Buffer
  /**
   * Finalize the compression stream. Writes the zstd frame footer.
   * Must be called once after all data has been transformed.
   */
  finish(): Buffer
}

/**
 * Streaming zstd decompression context.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * enabling chunked decompression of a zstd frame.
 */
export declare class ZstdDecompressContext {
  constructor()
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decoder needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decoder's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
}

/**
 * Streaming zstd decompression context with dictionary.
 *
 * Maintains internal decompression state across multiple `transform` calls,
 * using a pre-trained dictionary that matches the one used for compression.
 */
export declare class ZstdDecompressDictContext {
  constructor(dict: Buffer | Uint8Array)
  /**
   * Decompress a chunk of compressed data. Returns decompressed output
   * (may be empty if the decoder needs more data).
   */
  transform(chunk: Buffer | Uint8Array): Buffer
  /** Flush the decoder's internal buffer. Returns any buffered decompressed data. */
  flush(): Buffer
}

/**
 * Compress data using Brotli.
 *
 * Returns the compressed data as a Buffer.
 * Quality ranges from 0 (fastest) to 11 (best compression). Default is 6.
 */
export declare function brotliCompress(data: Buffer | Uint8Array, quality?: number | undefined | null): Buffer

/**
 * Asynchronously compress data using Brotli.
 *
 * Returns a Promise that resolves to the compressed data as a Buffer.
 * Quality ranges from 0 (fastest) to 11 (best compression). Default is 6.
 */
export declare function brotliCompressAsync(data: Buffer | Uint8Array, quality?: number | undefined | null): Promise<Buffer>

/**
 * Decompress Brotli-compressed data.
 *
 * Returns the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB.
 */
export declare function brotliDecompress(data: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress Brotli-compressed data.
 *
 * Returns a Promise that resolves to the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB.
 */
export declare function brotliDecompressAsync(data: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress Brotli-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function brotliDecompressWithCapacity(data: Buffer | Uint8Array, capacity: number): Buffer

/** Compression format detected from input data. */
export declare const enum CompressionFormat {
  Zstd = 'zstd',
  Gzip = 'gzip',
  Brotli = 'brotli',
  Unknown = 'unknown'
}

/**
 * Decompress data by auto-detecting the compression format.
 *
 * Detects the format from magic bytes and decompresses using the
 * appropriate algorithm. The maximum decompressed size is 256 MB
 * for all formats.
 *
 * Supported formats: zstd, gzip, brotli.
 * Raw deflate is not supported (no magic bytes to distinguish it).
 */
export declare function decompress(data: Buffer | Uint8Array): Buffer

/**
 * Compress data using raw deflate (no gzip header/trailer).
 *
 * Returns the compressed data as a Buffer.
 * Level ranges from 0 (no compression) to 9 (best compression). Default is 6.
 */
export declare function deflateCompress(data: Buffer | Uint8Array, level?: number | undefined | null): Buffer

/**
 * Asynchronously compress data using raw deflate (no gzip header/trailer).
 *
 * Returns a Promise that resolves to the compressed data as a Buffer.
 * Level ranges from 0 (no compression) to 9 (best compression). Default is 6.
 */
export declare function deflateCompressAsync(data: Buffer | Uint8Array, level?: number | undefined | null): Promise<Buffer>

/**
 * Decompress raw deflate-compressed data.
 *
 * Returns the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `deflateDecompressWithCapacity`
 * for larger data.
 */
export declare function deflateDecompress(data: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress raw deflate-compressed data.
 *
 * Returns a Promise that resolves to the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `deflateDecompressWithCapacity`
 * for larger data.
 */
export declare function deflateDecompressAsync(data: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress raw deflate-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function deflateDecompressWithCapacity(data: Buffer | Uint8Array, capacity: number): Buffer

/**
 * Detect the compression format of the given data.
 *
 * Returns `"zstd"`, `"gzip"`, or `"brotli"`.
 * Returns `"unknown"` if the format cannot be determined.
 *
 * Note: Brotli has no magic bytes, so it is detected by elimination.
 * Data that does not match zstd or gzip is reported as `"brotli"` only
 * if it appears to start with a valid brotli stream. Otherwise, `"unknown"`
 * is returned.
 */
export declare function detectFormat(data: Buffer | Uint8Array): CompressionFormat

/**
 * Compress data using gzip.
 *
 * Returns the compressed data as a Buffer.
 * Level ranges from 0 (no compression) to 9 (best compression). Default is 6.
 */
export declare function gzipCompress(data: Buffer | Uint8Array, level?: number | undefined | null): Buffer

/**
 * Asynchronously compress data using gzip.
 *
 * Returns a Promise that resolves to the compressed data as a Buffer.
 * Level ranges from 0 (no compression) to 9 (best compression). Default is 6.
 */
export declare function gzipCompressAsync(data: Buffer | Uint8Array, level?: number | undefined | null): Promise<Buffer>

/**
 * Decompress gzip-compressed data.
 *
 * Returns the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `gzipDecompressWithCapacity`
 * for larger data.
 */
export declare function gzipDecompress(data: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress gzip-compressed data.
 *
 * Returns a Promise that resolves to the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `gzipDecompressWithCapacity`
 * for larger data.
 */
export declare function gzipDecompressAsync(data: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress gzip-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function gzipDecompressWithCapacity(data: Buffer | Uint8Array, capacity: number): Buffer

/** Returns the library version. */
export declare function version(): string

/**
 * Compress data using Zstandard.
 *
 * Returns the compressed data as a Buffer.
 * Level ranges from 1 (fastest) to 22 (best compression). Default is 3.
 * Negative levels (e.g., -1 to -131072) enable fast mode, trading compression
 * ratio for speed. Level 0 is equivalent to the default level (3).
 */
export declare function zstdCompress(data: Buffer | Uint8Array, level?: number | undefined | null): Buffer

/**
 * Asynchronously compress data using Zstandard.
 *
 * Returns a Promise that resolves to the compressed data as a Buffer.
 * Level ranges from 1 (fastest) to 22 (best compression). Default is 3.
 * Negative levels (e.g., -1 to -131072) enable fast mode, trading compression
 * ratio for speed. Level 0 is equivalent to the default level (3).
 */
export declare function zstdCompressAsync(data: Buffer | Uint8Array, level?: number | undefined | null): Promise<Buffer>

/**
 * Compress data using Zstandard with a pre-trained dictionary.
 *
 * The same dictionary must be used for decompression via `zstdDecompressWithDict`.
 * Level ranges from 1 (fastest) to 22 (best compression). Default is 3.
 */
export declare function zstdCompressWithDict(data: Buffer | Uint8Array, dict: Buffer | Uint8Array, level?: number | undefined | null): Buffer

/**
 * Decompress Zstandard-compressed data.
 *
 * Returns the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `zstdDecompressWithCapacity`
 * for larger data.
 */
export declare function zstdDecompress(data: Buffer | Uint8Array): Buffer

/**
 * Asynchronously decompress Zstandard-compressed data.
 *
 * Returns a Promise that resolves to the decompressed data as a Buffer.
 * The maximum decompressed size is 256 MB. Use `zstdDecompressWithCapacity`
 * for larger data.
 */
export declare function zstdDecompressAsync(data: Buffer | Uint8Array): Promise<Buffer>

/**
 * Decompress Zstandard-compressed data with explicit capacity.
 *
 * Use this when the decompressed size exceeds the default 256 MB limit.
 * The `capacity` parameter specifies the maximum decompressed size in bytes.
 */
export declare function zstdDecompressWithCapacity(data: Buffer | Uint8Array, capacity: number): Buffer

/**
 * Decompress Zstandard-compressed data that was compressed with a dictionary.
 *
 * The same dictionary used for compression must be provided.
 */
export declare function zstdDecompressWithDict(data: Buffer | Uint8Array, dict: Buffer | Uint8Array): Buffer

/**
 * Train a zstd dictionary from sample data.
 *
 * The dictionary can be used with `zstdCompressWithDict` and `zstdDecompressWithDict`
 * to achieve better compression ratios on small, similar data.
 *
 * `maxDictSize` is optional and defaults to 110 KB (the zstd default).
 */
export declare function zstdTrainDictionary(samples: Array<Buffer | Uint8Array>, maxDictSize?: number | undefined | null): Buffer
