/* auto-generated by NAPI-RS */
/* eslint-disable */

// This header comes from crates/core/dts-header.d.ts ("dtsHeaderFile" in
// package.json). When the addon loads, it aliases [Symbol.dispose]() to
// close() on the stream context classes (crates/core/src/context.rs), which
// the declarations that napi-rs generates from the Rust code cannot express.

export interface BrotliCompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface BrotliCompressDictContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface BrotliDecompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface BrotliDecompressDictContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface DeflateCompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface DeflateDecompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface GzipCompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface GzipDecompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface Lz4CompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface Lz4DecompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface ZstdCompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface ZstdCompressDictContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface ZstdDecompressContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}

export interface ZstdDecompressDictContext {
  /** Close the context, like `close()`: `using` declarations call it. */
  [Symbol.dispose](): void;
}
